### PR TITLE
Small Optimization of XS Lookups

### PR DESCRIPTION
**Pull request by jtramm**
This PR adds the ability for a caller to control what kind of data gets passed back from the `Nuclide::calculate_xs()` function. Previously, this function always passed back an entire `NuclideMicroXS` struct, which included quite a lot of extra state variables that weren't needed in most places the function was called.

```C++
// Old
NuclideMicroXS Nuclide::calculate_xs(int i_log_union, Particle& p, bool depletion_rx_needed)
// New
void Nuclide::calculate_xs(int i_log_union, Particle& p, MicroXS* micro, double* reaction, NuclideMicroXS* cache)
```

The `MicroXS` struct contains only the four main reaction channels, which is typically all that's needed when building macroscopic cross sections. The `reaction` argument allows the caller to retrieve the depletion reactions. The `cache` argument allows the user to retrieve the full cache, which contains both the core XS values and the reaction values (if needed), along with all the other interpolation, ptable, scattering XS, etc data that is needed to complete a microscopic XS cache entry in the particle.

More info on this optimization is in PR #8, although we take a more limited approach here. In PR #8, I had proposed splitting the calculate_xs() functions up into a number of copies with each handling a different use case. While that is likely more optimal as there would be fewer conditionals in the kernel, the downside was it created a lot of copied code that would be a pain to manage going forward. Therefore, in this PR, I keep a single unified function.

Once all the components of PR #8 have been merged in, I can revisit how much might be gained from splitting the kernels up.

Current this PR gives (for A100, single rank, 8M particles in-flight):

  | Old | This PR
-- | -- | --
HM Large Inactive | 356 | 366
SMR Active | 165 | 162

Oddly, the "optimization" here appears to be slowing things down a little in active batches for the SMR. I'm not sure what might be causing this, but I am going to leave this PR in draft status until the other parts of PR #8 have been merged so we can see if that changes the value of this optimization.

### CODE REVIEW

**Comment by jtramm** [comment]
In re-running the test, I'm actually getting 161k for the baseline of the SMR on this card, so it does appear to be at least a small optimization for that problem rather than a regression.

**Comment by paulromano** [comment]
@jtramm Now that the other pieces have been merged, do you want to re-run the numbers on this one to see how it fares? Also, it looks like there's a conflict in tally_scoring.cpp that needs to be resolved.

**Comment by jtramm** [comment]
So with the nightly build of LLVM working again I went back and measured performance across the various branches. It looks like the optimization strategy that this PR takes is not going far enough, as it's not resulting in the gains we were getting in PR #8. Performance values (for A100, single rank, 8M particles in-flight):

  | openmp-target-offload | depletion_xs_opt (this PR) | tally_opt (PR #8)
-- | -- | -- | --
HM Large Inactive | 360 | 363 | 418
SMR Inactive | 212 | 215 | 236
SMR Active | 167 | 168 | 167

In PR #8, we were actually splitting the XS lookup function into several totally different versions depending on what was required from the function. In PR #8, we then actually decided on the host which version of the kernel to call, such that the kernels themselves could be a slim as possible. This seems to be great for making inactive batches as fast as possible, but the PR #8 strategy results in a lot of duplicated code. The strategy in this PR avoids the code duplication by just controlling what sorts of data gets passed to/from the functions, but appears to result in basically no performance gain.

So -- I think I'll need to keep hacking on this. I don't really like the idea of duplicating code as in PR #8, as it seems like it will make maintaining things tougher. I'l going to try to see if there's an easier way around this.

**Comment by paulromano** [comment]
Sounds good @jtramm, thanks for the update on this!

**Comment by jtramm** [comment]
I was able to find a decent way of doing this that avoids code duplication but still gets a good performance improvement.

After some experimentation, I found that the LLVM compiler was just not generating fast code if we were passing in a pointer to a struct for it to populate, e.g.:

```C++
void Nuclide::calculate_xs(int i_log_union, Particle& p, MicroXS* micro, double* reaction, NuclideMicroXS* cache)
```

was not as fast as if we directly passed back a stack object. I attempted to improve this by using the `__restrict__` keyword but that did not result in any improvements for the SMR problem.

The general problem is we have different things we need to pass back depending on who is calling the function. It gets called in three places right now (the material::calculate_xs function, in the collision function, and when scoring tallies). Each of these has different requirements for what it actually needs back from the function. The `tally_opt` branch was just making multiple copies of the function to handle each case, but that is a lot of duplicated code.

So, as a better solution, I just moved the calculate_xs function to the nuclide.h header and templated it as:

```C++
  template <typename T>
  T calculate_xs(int i_log_union, Particle& p, bool need_depletion_rx, double E, double sqrtkT)
  {...
```

Then, at the end of the function, we pass off all possible data to a constructor for T that gets returned to the caller:

```C++
    return T(
        total,
        absorption,
        fission,
        nu_fission,
        elastic,
        thermal,
        thermal_elastic,
        photon_prod,
        reaction,
        i_grid,
        i_temp,
        f,
        index_sab,
        index_temp_sab,
        sab_frac,
        use_ptable,
        E,
        sqrtkT);
```

I've defined constructors for the various types we want to pass back (`MicroXS`, `NuclideMicroXS`) that will only store the data that type actually contains, e.g.:

```C++
struct MicroXS {
  double total;         //!< macroscopic total xs
  double absorption;    //!< macroscopic absorption xs
  double fission;       //!< macroscopic fission xs
  double nu_fission;    //!< macroscopic production xs
  double reaction[DEPLETION_RX_SIZE];

  MicroXS() = default;

  MicroXS(
      double total,
      double absorption,
      double fission,
      double nu_fission,
      double elastic,
      double thermal,
      double thermal_elastic,
      double photon_prod,
      double reaction_in[DEPLETION_RX_SIZE],
      int index_grid,
      int index_temp,
      double interp_factor,
      int index_sab,
      int index_temp_sab,
      double sab_frac,
      bool use_ptable,
      double last_E,
      double last_sqrtkT
      ) :
    total(total),
    absorption(absorption),
    fission(fission),
    nu_fission(nu_fission)
  {
    for (int r = 0; r < DEPLETION_RX_SIZE; r++) {
      reaction[r] = reaction_in[r];
    }
  }

};
```

The upside here is we don't have duplicated code and its fast. The downside is we now have a rather large template function in a header, and we have a few goofy looking constructors for the `MicroXS` and `NuclideMicroXS` structs. If interested, one strategy we could potentially pursue is moving a lot of the logic out of the templated function and into smaller regular functions, then just having the templated function call a few higher level tasks. The downside is we have to manage passing a lot of arguments between those functions, so it's a little fiddly to implement, though not hard.

I'm also open to other ideas!

I also spotted something that I'd missed porting from PR #8 -- namely, that when storing data to the particle's macro_xs_ field at the end of a lookup, we only need to store the data we actually know rather than a full object copy. I've added in this optimization.

I also thought of another unrelated optimization for the lookup. Basically, we are accessing the particle's `E_` and sqrtkT_` fields a few times throughout the lookup (and in particular, at least once for every nuclide lookup), which is potentially a lot of loads when we could just load it once and store it in a register. We now just load the energy and temperature from the particle once and store them on the stack outside the loop over nuclides.

WIth that said, I re-ran our performance tests. I also realized I was running the SMR without multipole, so the new numbers for all branches are running the SMR with multipole now.

  | openmp-target-offload | depletion_xs_opt (this PR) | tally_opt (PR #8)
-- | -- | -- | --
HM Large Inactive | 360 | 419 | 418
SMR Inactive | 209 | 236 | 229
SMR Active | 178 | 198 | 174

This PR is now running faster than the `tally_opt` PR #8, so we are all caught up. Apologies for the large code delta due to templating the function. The only material changes to it were the prototype, the logic of what gets returned, and the change from accessing the particle's `E_` and `sqrtkT_` fields directly. So, the function does not need to be re-reviewed besides those areas.

**Review by paulromano — COMMENTED** [review]
I like the new approach! My only question is whether is it's possible to at least split up the big templated function to have URR/SAB lookups separate as we did before. I'm assuming there was a reason you ended up combining them all in one function but it's not obvious to me at first glance.

**Comment by jtramm** [comment]
Yes, this should be possible to split back up into smaller functions. However, I think one of the benefits we saw from inlining was that some compilers did better when we didn't have variables being passed by reference. I think there are probably decent ways around this by passing in as stack variables and having the return type be a tuple, but if we make that change I'd like to do some careful performance studies with all the compilers/GPUs to verify we aren't getting a performance penalty anywhere.

**Comment by paulromano** [comment]
OK, we can defer that for another day and another PR :smile: Thanks @jtramm!

**Review by paulromano — APPROVED** [review]

**Pull request merged**
